name: CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "context"
        env: 
          COMMIT_ID: ${{ github.sha }}
        run: ehco "Commit id => $COMMIT_ID"
